### ISSUE TITLE
Having issues it is saying can't find Patch XXXXX

### ISSUE THREAD

**Issue by hluckenbaugh** [iarsov/ansible-orapatch#10]
TASK [orapatch : Check OPatch minimum version] 

{
    "msg": "Patch '32218454'not found!'32218454'",
    "_ansible_no_log": false,
    "changed": false,
    "item": {
        "oracle_owner": "oracle",
        "oracle_home_path": "/u01/app/oracle/product/19.0.0/dbhome_1",
        "oratab_file": "/etc/oratab",
        "run_only_checks": false,
        "debug": true,
        "patch_id": "32218454",
        "patch_only_oh": false,
        "patch_ojvm": true,
        "patch_db_all": true,
        "patch_db_list": "dbtcity",
        "host": "vlfth-dbora19c",
        "backup_oh": false,
        "skip": false
    },
    "ansible_loop_var": "item",
    "_ansible_item_label": {
        "oracle_owner": "oracle",
        "oracle_home_path": "/u01/app/oracle/product/19.0.0/dbhome_1",
        "oratab_file": "/etc/oratab",
        "run_only_checks": false,
        "debug": true,
        "patch_id": "32218454",
        "patch_only_oh": false,
        "patch_ojvm": true,
        "patch_db_all": true,
        "patch_db_list": "dbtcity",
        "host": "vlfth-dbora19c",
        "backup_oh": false,
        "skip": false
    }

I also looked at the code but where does the Check Min Opatch Version know which version it should be looking for. I didn't see that in any of the code.

I am not feeding a root password because I am use AWX accessing the server as root and then becoming oracle userid.

**Comment by iarsov** [comment]
Hi hluckenbaugh,

The code where it checks the patch number is at _action_plugins/orapatch.py_ 

```
try:

    patch_item = patch_dict[patch_id]
    patch_item["patch_id"] = patch_id
    args["patch_item"] = patch_item

except Exception as e:

    result['failed'] = True
    result['msg'] = "Patch '" + str (patch_id) + "'not found!"
    result['msg'] += str (e)
    return result
```

**Comment by iarsov** [comment]
Check whether patch_dictionary.yml is properly configured. You can also see what you get for _patch_dict_ on line 99 in _action_plugins/orapatch.py_.

**Comment by hluckenbaugh** [comment]
Yes it is configured. I found that  when you try to pass that patch_id as a variable it doesn’t work.  When you put the patch number it works. I am trying to automate this with AWX where they enter all the variables and it works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iarsov** [comment]
I've updated the action plugin to cast "patch_id" as int(). That was the reason it was failing, string was failing to map to patch_dict.

**Comment by hluckenbaugh** [comment]
Ok great I will pull the latest Verison and see what happens

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
