### ISSUE TITLE
Failure to patch 19C

### ISSUE THREAD

**Issue by hluckenbaugh** [iarsov/ansible-orapatch#9]
When running your scripts I am getting this error on 19C.   I can't tell if this is a opatch issue or something else.

TASK [orapatch : Check OPatch minimum version] *********************************
task path: /tmp/awx_2708_bgxds5aj/project/AWX-Templates/oracle/roles/orapatch/tasks/main.yml:40
failed: [vlfth-dbora19c] (item={'oracle_owner': 'oracle', 'oracle_home_path': '/u01/app/oracle/product/19.0.0/dbhome_1', 'oratab_file': '/etc/oratab', 'run_only_checks': False, 'debug': False, 'patch_id': '32218454', 'patch_only_oh': False, 'patch_ojvm': True, 'patch_db_all': True, 'patch_db_list': 'dbtcity', 'host': 'vlfth-dbora19c', 'backup_oh': False, 'skip': False}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "backup_oh": false,
        "debug": false,
        "host": "vlfth-dbora19c",
        "oracle_home_path": "/u01/app/oracle/product/19.0.0/dbhome_1",
        "oracle_owner": "oracle",
        "oratab_file": "/etc/oratab",
        "patch_db_all": true,
        "patch_db_list": "dbtcity",
        "patch_id": "32218454",
        "patch_ojvm": true,
        "patch_only_oh": false,
        "run_only_checks": false,
        "skip": false
    },
    "msg": "Patch '32218454'not found!'32218454'"

here is what is in the dictionary file
# Defined Oracle patches
patch_dict:

  #""" 19.10.0.0.0 """
  32218454:
    patch_proactive_bp_id:
    patch_gi_id:
    patch_db_id: 32218454
    patch_ocw_id:
    patch_ojvm_id:
    patch_acfs_id:
    patch_dbwlm_id:
    patch_dir: /u01/app/oracle/product/19.0.0/dbhome_1/32218454
    file: p32218454_190000_Linux-x86-64.zip
    only_oh: False
    desc: "Database Release Update 19.0.0.0.0"

**Comment by iarsov** [comment]
Tracked via #10
